# Generated by Django 5.2.9 on 2026-01-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_device_view', '0002_multi_device_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceview',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
